
CREATE TABLE BD (
  UN LONG PRIMARY KEY,
  NOMBRE TEXT(255),
  TIPO TEXT(50),
  PREGUNTA MEMO,
  A TEXT(255), B TEXT(255), C TEXT(255), D TEXT(255),
  RA MEMO, RB MEMO, RC MEMO, RD MEMO,
  R TEXT(1),
  VIS BIT,
  COR BIT,
  REV BIT,
  ESTUDIO MEMO,
  Filtro LONG,
  OK LONG,
  KO LONG
);
