
CREATE TABLE BD (
  UN INTEGER PRIMARY KEY,
  NOMBRE TEXT,
  TIPO TEXT,
  PREGUNTA TEXT,
  A TEXT, B TEXT, C TEXT, D TEXT,
  RA TEXT, RB TEXT, RC TEXT, RD TEXT,
  R TEXT CHECK (R IN ('A','B','C','D')),
  VIS INTEGER DEFAULT 0,
  COR INTEGER DEFAULT 0,
  REV INTEGER DEFAULT 0,
  ESTUDIO TEXT,
  Filtro INTEGER DEFAULT 0,
  OK INTEGER DEFAULT 0,
  KO INTEGER DEFAULT 0
);
